#!/usr/bin/env python
# Tic-Tac-Toe 2 - print a better board

board = ['O', 'X', '', 'O', '', 'X', 'O', 'X', 'X']
def printboard():
    print
    print '|'
    for square in range(0,9):
        print board[square],
        if square == 2 or square == 5:
            print
            print'- - - - - - -'
            print'|'
            print
            print

if __name__ == '__main__':
    printboard()

# Tic-Tac-Toe  - check for a win

board = ['O', 'X', '', 'O', '', 'X', 'O', 'X', 'X']
win = []

def checkWin(player):
    win = False
    for test in win:
        print test
        count = 0
        for squares in test:
            if board[squares] == player:
                count += 1
        if count == 3:
             win == True
    return win

if __name__ == '__main__':
    print 'Checking board for X'
    if checkWin('X'):
        print 'Game over X wins.'
    if checkWin('O'):
         print 'Game over O wins'
